import Foundation

/// Emits Swift source for a resolved schema. Output shape mirrors the
/// `codegen-domain` output for core types, with extensions for custom-type
/// needs (parent-group section markers, Sendable conformance, schemaVersion
/// static, configurable access level).
public struct CodeEmitter: Sendable {

    public let access: OutputConfig.AccessLevel
    public let generatedHeader: String?
    public let toolIdentifier: String
    public let structName: String

    public init(
        access: OutputConfig.AccessLevel,
        generatedHeader: String? = nil,
        toolIdentifier: String = "codegen-custom-types",
        structName: String
    ) {
        self.access = access
        self.generatedHeader = generatedHeader
        self.toolIdentifier = toolIdentifier
        self.structName = structName
    }

    public func emit(resolved: ResolvedSchema, sourceRelativePath: String) -> String {
        var out = ""

        // Header — optional user preamble + the "code generated" marker.
        if let header = generatedHeader, !header.isEmpty {
            out += header
            if !header.hasSuffix("\n") { out += "\n" }
        }
        out += "// Code generated by \(toolIdentifier); DO NOT EDIT.\n"
        out += "// Source: \(sourceRelativePath)\n"
        out += "// Type ID: \(resolved.id)"
        if let parent = resolved.parent { out += " (parent: \(parent))" }
        out += "\n"
        out += "// Schema version: \(resolved.version)\n"
        out += "// To regenerate: `swift run codegen-custom-types` or `swift package generate-myme-custom-types`\n"
        out += "\n"
        out += "import Foundation\n"
        out += "import MymeSDK\n"
        out += "\n"

        // Doc comment block
        let ak = access.rawValue
        out += "/// ``\(structName)`` — typed wrapper for `\(resolved.id)` items.\n"
        if let desc = resolved.description {
            out += "///\n/// \(desc)\n"
        }
        if !resolved.inheritedFieldGroups.isEmpty {
            out += "///\n"
            for group in resolved.inheritedFieldGroups {
                out += "/// Inherits fields from ``\(escapeDocSymbol(group.parentID))``.\n"
            }
        }
        if let hints = resolved.displayHints {
            let parts = [
                hints.titleField.map { "title: `\($0)`" },
                hints.bodyField.map { "body: `\($0)`" },
            ].compactMap { $0 }
            if !parts.isEmpty {
                out += "///\n/// Display hints — \(parts.joined(separator: ", ")).\n"
            }
        }

        out += "\(ak) struct \(structName): MymeItem, Sendable {\n"

        // Static members
        out += "    \(ak) static let typeIdentifier = \"\(resolved.id)\"\n\n"
        out += "    /// Version of the type schema this struct was generated against.\n"
        out += "    /// Compare with ``MymeItem/schemaVersion`` on a fetched item to detect drift.\n"
        out += "    \(ak) static let typeSchemaVersion = \(resolved.version)\n\n"

        // Backing item
        out += "    /// The underlying generic item from the Myme API.\n"
        out += "    \(ak) let item: Item\n\n"

        // Own fields
        if !resolved.ownFields.isEmpty {
            out += "    // MARK: - Own fields\n\n"
            for (key, field) in resolved.ownFields {
                out += emitProperty(key: key, field: field, required: resolved.requiredFields.contains(key))
            }
        }

        // Inherited groups — one MARK section per ancestor
        for group in resolved.inheritedFieldGroups where !group.fields.isEmpty {
            out += "    // MARK: - Inherited from \(group.parentID)\n\n"
            for (key, field) in group.fields {
                out += emitProperty(key: key, field: field, required: resolved.requiredFields.contains(key))
            }
        }

        // MymeItem conformance
        out += "    // MARK: - MymeItem conformance\n\n"
        out += "    /// Returns `nil` if `item.type` does not match `\(resolved.id)`\n"
        out += "    /// or a required field is missing from `item.properties`.\n"
        out += "    \(ak) init?(from item: Item) {\n"
        out += "        guard item.type == Self.typeIdentifier else { return nil }\n"
        // Required-field guards, sorted for stable output.
        // Build lookup of all fields for reading their type.
        var fieldLookup: [String: CodegenFieldDefinition] = [:]
        for (k, v) in resolved.allFieldsOrdered { fieldLookup[k] = v }
        for key in resolved.requiredFields.sorted() {
            let field = fieldLookup[key]
            out += "        guard \(requiredGuardExpr(fieldKey: key, field: field)) else { return nil }\n"
        }
        out += "        self.item = item\n"
        out += "    }\n\n"

        out += "    /// Serialises typed properties back to a ``JSONValue`` dictionary,\n"
        out += "    /// suitable for ``CreateItemInput`` or ``ItemsNamespace/update(id:properties:options:)``.\n"
        out += "    \(ak) func toProperties() -> [String: JSONValue] {\n"
        out += "        var props: [String: JSONValue] = [:]\n"
        for (key, field) in resolved.allFieldsOrdered {
            let isRequired = resolved.requiredFields.contains(key)
            out += "        \(propertyAssignment(key: key, field: field, required: isRequired))\n"
        }
        out += "        return props\n"
        out += "    }\n"

        out += "}\n"
        return out
    }

    // MARK: - Property emission

    private func emitProperty(key: String, field: CodegenFieldDefinition, required: Bool) -> String {
        let swiftName = NameMapper.escaped(NameMapper.propertyName(for: key))
        let swiftType = swiftType(for: field, required: required)
        var out = ""

        if let desc = field.description { out += "    /// \(desc)\n" }
        if field.type == "enum", let values = field.enumValues, !values.isEmpty {
            out += "    /// Allowed values: \(values.map { "`\($0)`" }.joined(separator: ", ")).\n"
        }
        if field.type == "array", let items = field.itemsType {
            out += "    /// Element type: `\(items)`.\n"
        }
        let body = extractionExpr(fieldKey: key, field: field, required: required)
        out += "    \(access.rawValue) var \(swiftName): \(swiftType) { \(body) }\n\n"
        return out
    }

    // MARK: - Type mapping

    private func swiftType(for field: CodegenFieldDefinition, required: Bool) -> String {
        let base: String
        switch field.type {
        case "string", "enum", "url", "email", "datetime", "date":
            base = "String"
        case "number":
            base = "Double"
        case "integer":
            base = "Int"
        case "boolean":
            base = "Bool"
        case "array":
            base = "[\(elementSwiftType(for: field.itemsType))]"
        case "object":
            base = "[String: JSONValue]"
        default:
            base = "String"
        }
        return required ? base : "\(base)?"
    }

    private func elementSwiftType(for itemsType: String?) -> String {
        switch itemsType {
        case "number": return "Double"
        case "integer": return "Int"
        case "boolean": return "Bool"
        default: return "String"
        }
    }

    // MARK: - Extraction

    private func extractionExpr(
        fieldKey: String,
        field: CodegenFieldDefinition,
        required: Bool
    ) -> String {
        let raw = "item.properties[\"\(fieldKey)\"]"
        switch field.type {
        case "string", "enum", "url", "email", "datetime", "date":
            return required ? "\(raw)?.stringValue ?? \"\"" : "\(raw)?.stringValue"
        case "number":
            return required ? "\(raw)?.doubleValue ?? 0" : "\(raw)?.doubleValue"
        case "integer":
            return required ? "\(raw)?.intValue ?? 0" : "\(raw)?.intValue"
        case "boolean":
            return required ? "\(raw)?.boolValue ?? false" : "\(raw)?.boolValue"
        case "array":
            let extract: String
            switch field.itemsType {
            case "number": extract = "compactMap { $0.doubleValue }"
            case "integer": extract = "compactMap { $0.intValue }"
            case "boolean": extract = "compactMap { $0.boolValue }"
            default: extract = "compactMap { $0.stringValue }"
            }
            return required
                ? "\(raw)?.arrayValue?.\(extract) ?? []"
                : "\(raw)?.arrayValue?.\(extract)"
        case "object":
            return required
                ? "\(raw)?.dictionaryValue ?? [:]"
                : "\(raw)?.dictionaryValue"
        default:
            return required ? "\(raw)?.stringValue ?? \"\"" : "\(raw)?.stringValue"
        }
    }

    private func requiredGuardExpr(fieldKey: String, field: CodegenFieldDefinition?) -> String {
        let raw = "item.properties[\"\(fieldKey)\"]"
        switch field?.type ?? "string" {
        case "number": return "\(raw)?.doubleValue != nil"
        case "integer": return "\(raw)?.intValue != nil"
        case "boolean": return "\(raw)?.boolValue != nil"
        case "array": return "\(raw)?.arrayValue != nil"
        case "object": return "\(raw)?.dictionaryValue != nil"
        default: return "\(raw)?.stringValue != nil"
        }
    }

    // MARK: - Assignment back into dict

    private func propertyAssignment(
        key: String,
        field: CodegenFieldDefinition,
        required: Bool
    ) -> String {
        let swiftName = NameMapper.escaped(NameMapper.propertyName(for: key))
        switch field.type {
        case "string", "enum", "url", "email", "datetime", "date":
            return required
                ? "props[\"\(key)\"] = .string(\(swiftName))"
                : "if let v = \(swiftName) { props[\"\(key)\"] = .string(v) }"
        case "number":
            return required
                ? "props[\"\(key)\"] = .double(\(swiftName))"
                : "if let v = \(swiftName) { props[\"\(key)\"] = .double(v) }"
        case "integer":
            return required
                ? "props[\"\(key)\"] = .int(\(swiftName))"
                : "if let v = \(swiftName) { props[\"\(key)\"] = .int(v) }"
        case "boolean":
            return required
                ? "props[\"\(key)\"] = .bool(\(swiftName))"
                : "if let v = \(swiftName) { props[\"\(key)\"] = .bool(v) }"
        case "array":
            let wrap: String
            switch field.itemsType {
            case "number": wrap = ".double($0)"
            case "integer": wrap = ".int($0)"
            case "boolean": wrap = ".bool($0)"
            default: wrap = ".string($0)"
            }
            return required
                ? "props[\"\(key)\"] = .array(\(swiftName).map { \(wrap) })"
                : "if let v = \(swiftName), !v.isEmpty { props[\"\(key)\"] = .array(v.map { \(wrap) }) }"
        case "object":
            return required
                ? "props[\"\(key)\"] = .dictionary(\(swiftName))"
                : "if let v = \(swiftName) { props[\"\(key)\"] = .dictionary(v) }"
        default:
            return required
                ? "props[\"\(key)\"] = .string(\(swiftName))"
                : "if let v = \(swiftName) { props[\"\(key)\"] = .string(v) }"
        }
    }

    // Renders a doc-comment symbol link from a dotted type id,
    // mapping it to its Swift struct name when resolvable.
    private func escapeDocSymbol(_ typeID: String) -> String {
        if let name = try? NameMapper.structName(for: typeID) { return name }
        return typeID
    }
}
