// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
extension Components {
    /// Types generated from the `#/components/headers` section of the OpenAPI document.
    public enum Headers {
        /// The contract version this server speaks, the same integer as the document's `info.version` and the root's `contract`. Sent on every response the application gives, refusals included, so a client can check the answer it is about to read. A client generated for another number cannot trust the body. A request refused by the HTTP layer before it reaches the application, such as one with a malformed host, is answered without it.
        ///
        /// - Remark: Generated from `#/components/headers/X-Marfa-Contract`.
        public typealias XMarfaContract = Swift.Int
        /// A matching opaque read-view certificate, supplied only after a conditional copy read and its snapshot have completed. Successful conditional reads and snapshot-attributed resource refusals carry it with Cache-Control: no-store. Ordinary reads and write receipts carry none.
        ///
        /// - Remark: Generated from `#/components/headers/X-Marfa-Read-View`.
        public typealias XMarfaReadView = Swift.String
        /// This request's identifier, the same one written to the server's request log. Echoes the caller's own `X-Request-ID` when it sends one matching `[A-Za-z0-9_-]{1,128}`, and is a generated UUIDv7 otherwise, so a client can either adopt the server's id or impose its own. Quote it when reporting a problem: it is the one value that finds the request again.
        ///
        /// - Remark: Generated from `#/components/headers/X-Request-ID`.
        public typealias XRequestID = Swift.String
        /// The machine-readable error code, identical to `error.code` in the body and drawn from the same enum the response schema lists. Read it rather than matching on `error.message`, which is prose written for a person and may be reworded. Present on every error the server renders, including one served from an idempotency record.
        ///
        /// - Remark: Generated from `#/components/headers/X-Error-Code`.
        public typealias XErrorCode = Swift.String
        /// How many requests this credential may make against this path group in the current window. Sent on every response, not only refusals, so a client can pace itself before it is refused. A second window bounds what one credential spends across every path group together, and a refusal from that one carries this trio unchanged — so a 429 may arrive with requests apparently left. Absent entirely on a deployment that does not enable rate limiting, along with the rest of the `X-RateLimit-*` trio.
        ///
        /// - Remark: Generated from `#/components/headers/X-RateLimit-Limit`.
        public typealias XRateLimitLimit = Swift.Int
        /// Requests left in this path group's window for this credential, floored at 0. A 429 from that window is the one that reads 0; a 429 from the credential-wide window described above can read more.
        ///
        /// - Remark: Generated from `#/components/headers/X-RateLimit-Remaining`.
        public typealias XRateLimitRemaining = Swift.Int
        /// Unix time in seconds at which the current window ends and `X-RateLimit-Remaining` returns to `X-RateLimit-Limit`.
        ///
        /// - Remark: Generated from `#/components/headers/X-RateLimit-Reset`.
        public typealias XRateLimitReset = Swift.Int
        /// Seconds to wait before retrying, sent with the rate limiter's refusal. Derived from the time left in the window rather than a fixed backoff, so a client that honors it needs no backoff of its own.
        ///
        /// - Remark: Generated from `#/components/headers/Retry-After`.
        public typealias RetryAfter = Swift.Int
        /// Sent as `true` when this response was served from the record of an earlier request carrying the same `Idempotency-Key`, rather than by performing the write. It is only ever sent on a replay and only with that value, so its absence means the write was performed. The status and body are the first attempt's, which is why the header can arrive on an error: a recorded 409 replays as a 409. Read a replayed response exactly as the original would have been read — the header says where the answer came from, not that anything went wrong.
        ///
        /// - Remark: Generated from `#/components/headers/Idempotency-Replayed`.
        @frozen public enum IdempotencyReplayed: String, Codable, Hashable, Sendable, CaseIterable {
            case _true = "true"
        }
    }
}
