// CompileCheckTests — the target itself is the test.
//
// The sibling .swift files in this directory are pre-generated by
// `codegen-custom-types` against fixture schemas in `Fixtures/schemas/`.
// If the generator's output shape ever regresses (e.g. a protocol
// requirement changes or a JSONValue accessor moves), these files stop
// compiling and the whole target fails to build — no runtime needed.
//
// To refresh:
//   1. Update Fixtures/schemas/*.json
//   2. Run codegen against them with --config pointing at a temp dir
//   3. Copy the output Swift files over these ones

import Testing
import MymeSDK

@Suite struct CompileCheckTests {

    @Test func generatedTypesConformToMymeItem() {
        #expect(MyappBooking.typeIdentifier == "myapp.booking")
        #expect(MyappSimpleNote.typeIdentifier == "myapp.simple_note")
        #expect(MyappAllTypes.typeIdentifier == "myapp.all_types")
        #expect(MyappKeywordFields.typeIdentifier == "myapp.keyword_fields")
        #expect(MyappBaseDerived.typeIdentifier == "myapp.base.derived")
        #expect(MyappBase.typeIdentifier == "myapp.base")
    }

    @Test func typeSchemaVersionIsExposed() {
        #expect(MyappBooking.typeSchemaVersion == 1)
    }
}
