// Code generated by codegen-custom-types; DO NOT EDIT.
// Source: MymeTypes/myapp.base.json
// Type ID: myapp.base
// Schema version: 1
// To regenerate: `swift run codegen-custom-types` or `swift package generate-myme-custom-types`

import Foundation
import MymeSDK

/// ``MyappBase`` — typed wrapper for `myapp.base` items.
///
/// Top of a two-level custom inheritance chain.
public struct MyappBase: MymeItem, Sendable {
    public static let typeIdentifier = "myapp.base"

    /// Version of the type schema this struct was generated against.
    /// Compare with ``MymeItem/schemaVersion`` on a fetched item to detect drift.
    public static let typeSchemaVersion = 1

    /// The underlying generic item from the Myme API.
    public let item: Item

    // MARK: - Own fields

    /// Who owns this
    public var owner: String { item.properties["owner"]?.stringValue ?? "" }

    // MARK: - MymeItem conformance

    /// Returns `nil` if `item.type` does not match `myapp.base`
    /// or a required field is missing from `item.properties`.
    public init?(from item: Item) {
        guard item.type == Self.typeIdentifier else { return nil }
        guard item.properties["owner"]?.stringValue != nil else { return nil }
        self.item = item
    }

    /// Serialises typed properties back to a ``JSONValue`` dictionary,
    /// suitable for ``CreateItemInput`` or ``ItemsNamespace/update(id:properties:options:)``.
    public func toProperties() -> [String: JSONValue] {
        var props: [String: JSONValue] = [:]
        props["owner"] = .string(owner)
        return props
    }
}
