// Code generated by codegen-custom-types; DO NOT EDIT.
// Source: MymeTypes/myapp.all_types.json
// Type ID: myapp.all_types
// Schema version: 1
// To regenerate: `swift run codegen-custom-types` or `swift package generate-myme-custom-types`

import Foundation
import MymeSDK

/// ``MyappAllTypes`` — typed wrapper for `myapp.all_types` items.
///
/// Exercises every FieldType the emitter supports.
public struct MyappAllTypes: MymeItem, Sendable {
    public static let typeIdentifier = "myapp.all_types"

    /// Version of the type schema this struct was generated against.
    /// Compare with ``MymeItem/schemaVersion`` on a fetched item to detect drift.
    public static let typeSchemaVersion = 1

    /// The underlying generic item from the Myme API.
    public let item: Item

    // MARK: - Own fields

    /// A plain string
    public var title: String { item.properties["title"]?.stringValue ?? "" }

    /// Integer
    public var count: Int? { item.properties["count"]?.intValue }

    /// Flag
    public var isActive: Bool? { item.properties["is_active"]?.boolValue }

    /// A URL
    public var link: String? { item.properties["link"]?.stringValue }

    /// Free-form dictionary
    public var metadata: [String: JSONValue]? { item.properties["metadata"]?.dictionaryValue }

    /// Floating-point
    public var rating: Double? { item.properties["rating"]?.doubleValue }

    /// Status enum
    /// Allowed values: `draft`, `published`, `archived`.
    public var status: String? { item.properties["status"]?.stringValue }

    /// List of tags
    /// Element type: `string`.
    public var tags: [String]? { item.properties["tags"]?.arrayValue?.compactMap { $0.stringValue } }

    // MARK: - MymeItem conformance

    /// Returns `nil` if `item.type` does not match `myapp.all_types`
    /// or a required field is missing from `item.properties`.
    public init?(from item: Item) {
        guard item.type == Self.typeIdentifier else { return nil }
        guard item.properties["title"]?.stringValue != nil else { return nil }
        self.item = item
    }

    /// Serialises typed properties back to a ``JSONValue`` dictionary,
    /// suitable for ``CreateItemInput`` or ``ItemsNamespace/update(id:properties:options:)``.
    public func toProperties() -> [String: JSONValue] {
        var props: [String: JSONValue] = [:]
        props["title"] = .string(title)
        if let v = count { props["count"] = .int(v) }
        if let v = isActive { props["is_active"] = .bool(v) }
        if let v = link { props["link"] = .string(v) }
        if let v = metadata { props["metadata"] = .dictionary(v) }
        if let v = rating { props["rating"] = .double(v) }
        if let v = status { props["status"] = .string(v) }
        if let v = tags, !v.isEmpty { props["tags"] = .array(v.map { .string($0) }) }
        return props
    }
}
