// Code generated by codegen-custom-types; DO NOT EDIT.
// Source: MymeTypes/myapp.simple_note.json
// Type ID: myapp.simple_note
// Schema version: 1
// To regenerate: `swift run codegen-custom-types` or `swift package generate-myme-custom-types`

import Foundation
import MymeSDK

/// ``MyappSimpleNote`` — typed wrapper for `myapp.simple_note` items.
///
/// Standalone type, no parent, one optional field.
public struct MyappSimpleNote: MymeItem, Sendable {
    public static let typeIdentifier = "myapp.simple_note"

    /// Version of the type schema this struct was generated against.
    /// Compare with ``MymeItem/schemaVersion`` on a fetched item to detect drift.
    public static let typeSchemaVersion = 1

    /// The underlying generic item from the Myme API.
    public let item: Item

    // MARK: - Own fields

    /// The note text
    public var body: String? { item.properties["body"]?.stringValue }

    // MARK: - MymeItem conformance

    /// Returns `nil` if `item.type` does not match `myapp.simple_note`
    /// or a required field is missing from `item.properties`.
    public init?(from item: Item) {
        guard item.type == Self.typeIdentifier else { return nil }
        self.item = item
    }

    /// Serialises typed properties back to a ``JSONValue`` dictionary,
    /// suitable for ``CreateItemInput`` or ``ItemsNamespace/update(id:properties:options:)``.
    public func toProperties() -> [String: JSONValue] {
        var props: [String: JSONValue] = [:]
        if let v = body { props["body"] = .string(v) }
        return props
    }
}
