// Code generated by codegen-custom-types; DO NOT EDIT.
// Source: MymeTypes/myapp.base.derived.json
// Type ID: myapp.base.derived (parent: myapp.base)
// Schema version: 1
// To regenerate: `swift run codegen-custom-types` or `swift package generate-myme-custom-types`

import Foundation
import MymeSDK

/// ``MyappBaseDerived`` — typed wrapper for `myapp.base.derived` items.
///
/// Custom child with a custom parent — chain resolves client-side.
///
/// Inherits fields from ``MyappBase``.
public struct MyappBaseDerived: MymeItem, Sendable {
    public static let typeIdentifier = "myapp.base.derived"

    /// Version of the type schema this struct was generated against.
    /// Compare with ``MymeItem/schemaVersion`` on a fetched item to detect drift.
    public static let typeSchemaVersion = 1

    /// The underlying generic item from the Myme API.
    public let item: Item

    // MARK: - Own fields

    /// Child-only field
    public var extra: String? { item.properties["extra"]?.stringValue }

    // MARK: - Inherited from myapp.base

    /// Who owns this
    public var owner: String { item.properties["owner"]?.stringValue ?? "" }

    // MARK: - MymeItem conformance

    /// Returns `nil` if `item.type` does not match `myapp.base.derived`
    /// or a required field is missing from `item.properties`.
    public init?(from item: Item) {
        guard item.type == Self.typeIdentifier else { return nil }
        guard item.properties["owner"]?.stringValue != nil else { return nil }
        self.item = item
    }

    /// Serialises typed properties back to a ``JSONValue`` dictionary,
    /// suitable for ``CreateItemInput`` or ``ItemsNamespace/update(id:properties:options:)``.
    public func toProperties() -> [String: JSONValue] {
        var props: [String: JSONValue] = [:]
        if let v = extra { props["extra"] = .string(v) }
        props["owner"] = .string(owner)
        return props
    }
}
