// Code generated by codegen-custom-types; DO NOT EDIT.
// Source: MymeTypes/myapp.keyword_fields.json
// Type ID: myapp.keyword_fields
// Schema version: 1
// To regenerate: `swift run codegen-custom-types` or `swift package generate-myme-custom-types`

import Foundation
import MymeSDK

/// ``MyappKeywordFields`` — typed wrapper for `myapp.keyword_fields` items.
///
/// Fields whose names collide with Swift keywords — must emit with backtick escaping.
public struct MyappKeywordFields: MymeItem, Sendable {
    public static let typeIdentifier = "myapp.keyword_fields"

    /// Version of the type schema this struct was generated against.
    /// Compare with ``MymeItem/schemaVersion`` on a fetched item to detect drift.
    public static let typeSchemaVersion = 1

    /// The underlying generic item from the Myme API.
    public let item: Item

    // MARK: - Own fields

    /// Escapable via backticks
    public var `class`: String? { item.properties["class"]?.stringValue }

    /// Another keyword
    public var `init`: String? { item.properties["init"]?.stringValue }

    /// Normal field for contrast
    public var safeField: String? { item.properties["safe_field"]?.stringValue }

    // MARK: - MymeItem conformance

    /// Returns `nil` if `item.type` does not match `myapp.keyword_fields`
    /// or a required field is missing from `item.properties`.
    public init?(from item: Item) {
        guard item.type == Self.typeIdentifier else { return nil }
        self.item = item
    }

    /// Serialises typed properties back to a ``JSONValue`` dictionary,
    /// suitable for ``CreateItemInput`` or ``ItemsNamespace/update(id:properties:options:)``.
    public func toProperties() -> [String: JSONValue] {
        var props: [String: JSONValue] = [:]
        if let v = `class` { props["class"] = .string(v) }
        if let v = `init` { props["init"] = .string(v) }
        if let v = safeField { props["safe_field"] = .string(v) }
        return props
    }
}
