// Code generated by codegen-custom-types; DO NOT EDIT.
// Source: MarfaTypes/myapp.booking.json
// Type ID: myapp.booking (parent: core.note)
// Schema version: 1
// To regenerate: `swift run codegen-custom-types` or `swift package generate-marfa-custom-types`

import Foundation
import MarfaSDK

/// ``MyappBooking`` — typed wrapper for `myapp.booking` items.
///
/// A time-bounded reservation against a person or place.
///
/// Inherits fields from ``CoreNote``.
///
/// Display hints — title: `title`, body: `body`.
public struct MyappBooking: MarfaItem, Sendable {
    public static let typeIdentifier = "myapp.booking"

    /// Version of the type schema this struct was generated against.
    /// Compare with ``MarfaItem/schemaVersion`` on a fetched item to detect drift.
    public static let typeSchemaVersion = 1

    /// The underlying generic item from the Marfa API.
    public let item: Item

    // MARK: - Own fields

    /// Start of the booking
    public var startAt: String { item.properties["start_at"]?.stringValue ?? "" }

    /// Number of guests
    public var partySize: Int? { item.properties["party_size"]?.intValue }

    // MARK: - Inherited from core.note

    /// The note text
    public var body: String { item.properties["body"]?.stringValue ?? "" }

    /// BCP 47 language code
    public var language: String? { item.properties["language"]?.stringValue }

    /// Personal annotations
    public var notes: String? { item.properties["notes"]?.stringValue }

    /// Heading or title
    public var title: String? { item.properties["title"]?.stringValue }

    // MARK: - MarfaItem conformance

    /// Returns `nil` if `item.type` does not match `myapp.booking`
    /// or a required field is missing from `item.properties`.
    public init?(from item: Item) {
        guard item.type == Self.typeIdentifier else { return nil }
        guard item.properties["body"]?.stringValue != nil else { return nil }
        guard item.properties["start_at"]?.stringValue != nil else { return nil }
        self.item = item
    }

    /// Serialises typed properties back to a ``JSONValue`` dictionary,
    /// suitable for ``CreateItemInput`` or ``ItemsNamespace/update(id:properties:options:)``.
    public func toProperties() -> [String: JSONValue] {
        var props: [String: JSONValue] = [:]
        props["start_at"] = .string(startAt)
        if let v = partySize { props["party_size"] = .int(v) }
        props["body"] = .string(body)
        if let v = language { props["language"] = .string(v) }
        if let v = notes { props["notes"] = .string(v) }
        if let v = title { props["title"] = .string(v) }
        return props
    }
}
