#!/usr/bin/env swift
// codegen-domain.swift — generates typed Swift domain-model structs from the
// vendored Marfa core type registry (scripts/core-types/*.json).
//
// Usage (from repo root):
//   swift run codegen-domain
//
// Output: Sources/MarfaSDK/DomainModels/Generated/*.swift
// Each file carries a "Code generated by codegen-domain; DO NOT EDIT." header.
// Hand-edits will be overwritten on the next run.
//
// Freshness check (CI):
//   swift run codegen-domain && git diff --exit-code Sources/MarfaSDK/DomainModels/Generated/

import Foundation

// MARK: - JSON schema types

struct FieldDefinition: Decodable {
    let type: String
    let description: String?
    let format: String?
    let enumValues: [String]?
    let itemsType: String?
    /// Upper bound on an array field's element count. No vendored type
    /// declares one today; it is decoded because the server's field
    /// definition carries it and a custom type may.
    let maxItems: Int?

    enum CodingKeys: String, CodingKey {
        case type, description, format
        case enumValues = "enum_values"
        case itemsType = "items_type"
        case maxItems
    }
}

struct DisplayHints: Decodable {
    let titleField: String?
    let bodyField: String?

    enum CodingKeys: String, CodingKey {
        case titleField = "title_field"
        case bodyField = "body_field"
    }
}

struct TypeSchema: Decodable {
    let id: String
    let parent: String?
    let label: String?
    let description: String?
    let version: Int
    let fields: [String: FieldDefinition]
    let required: [String]
    let displayHints: DisplayHints?
    let deferred: Bool?

    enum CodingKeys: String, CodingKey {
        case id, parent, label, description, version, fields, required
        case displayHints = "display_hints"
        case deferred = "_deferred"
    }
}

// MARK: - Helpers

/// Maps a type-schema field type + format to a Swift type name.
/// Required fields are non-optional; optional fields append `?`.
func swiftType(for field: FieldDefinition, required: Bool) -> String {
    let base: String
    switch field.type {
    case "string":
        // All string subtypes (url, email, datetime, date, bcp47, iso3166, …) stay String.
        base = "String"
    case "number":
        base = "Double"
    case "integer":
        base = "Int"
    case "boolean":
        base = "Bool"
    case "enum":
        // Enums surface as String; enum_values documented in comments.
        base = "String"
    case "array":
        let items = field.itemsType ?? "String"
        let elementType: String
        switch items {
        case "string": elementType = "String"
        case "number": elementType = "Double"
        case "integer": elementType = "Int"
        case "boolean": elementType = "Bool"
        default: elementType = "String"
        }
        base = "[\(elementType)]"
    case "object":
        base = "[String: JSONValue]"
    default:
        base = "String"
    }
    return required ? base : "\(base)?"
}

/// Swift reserved words that need backtick escaping when used as
/// identifiers. Field names like `public`, `private`, `default` etc. on
/// upstream core types (e.g. `raindrop.collection.public`) trip the
/// compiler otherwise. Conservative list — extends as new collisions
/// surface.
let swiftReservedWords: Set<String> = [
    "associatedtype", "class", "deinit", "enum", "extension", "fileprivate",
    "func", "import", "init", "inout", "internal", "let", "open", "operator",
    "private", "protocol", "public", "rethrows", "static", "struct", "subscript",
    "typealias", "var", "break", "case", "catch", "continue", "default", "defer",
    "do", "else", "fallthrough", "for", "guard", "if", "in", "repeat", "return",
    "switch", "throw", "throws", "where", "while", "as", "false", "is", "nil",
    "self", "Self", "super", "true", "try",
]

/// Wraps a Swift identifier in backticks if it collides with a reserved
/// word. Otherwise returns the identifier unchanged.
func escapeIfReserved(_ identifier: String) -> String {
    swiftReservedWords.contains(identifier) ? "`\(identifier)`" : identifier
}

/// Converts a snake_case field name to lowerCamelCase Swift identifier,
/// backtick-escaping if the result collides with a Swift reserved word.
func camelCase(_ snake: String) -> String {
    let parts = snake.split(separator: "_", omittingEmptySubsequences: true)
    guard let first = parts.first else { return escapeIfReserved(snake) }
    let raw = String(first) + parts.dropFirst().map { $0.prefix(1).uppercased() + $0.dropFirst() }.joined()
    return escapeIfReserved(raw)
}

/// Converts a type ID to a Swift struct name: "core.entity.person" → "CoreEntityPerson".
/// Underscores split like dots do, which custom type ids can carry.
func structName(for typeId: String) -> String {
    typeId
        .split(separator: ".")
        .flatMap { $0.split(separator: "_") }
        .map { $0.prefix(1).uppercased() + $0.dropFirst() }
        .joined()
}

/// Resolves the full set of fields for a type, walking the parent chain.
/// Child fields shadow parent fields (child wins on collision — only happens
/// for body in core.media.article which intentionally narrows the description).
func resolvedFields(
    for schema: TypeSchema,
    registry: [String: TypeSchema]
) -> [(key: String, value: FieldDefinition)] {
    var chain: [TypeSchema] = [schema]
    var current = schema
    while let parentId = current.parent, let parent = registry[parentId] {
        chain.append(parent)
        current = parent
    }
    // Walk from root → leaf; child overrides parent for same key.
    var merged: [(key: String, value: FieldDefinition)] = []
    var seen = Set<String>()
    // Reverse so root comes first, then children override.
    for ancestor in chain.reversed() {
        for (key, field) in ancestor.fields.sorted(by: { $0.key < $1.key }) {
            if !seen.contains(key) {
                merged.append((key, field))
                seen.insert(key)
            }
        }
    }
    // Re-sort alphabetically for stable output; required fields first.
    let requiredSet = resolvedRequired(for: schema, registry: registry)
    merged.sort {
        let aReq = requiredSet.contains($0.key)
        let bReq = requiredSet.contains($1.key)
        if aReq != bReq { return aReq }
        return $0.key < $1.key
    }
    return merged
}

func resolvedRequired(
    for schema: TypeSchema,
    registry: [String: TypeSchema]
) -> Set<String> {
    var required = Set(schema.required)
    var current = schema
    while let parentId = current.parent, let parent = registry[parentId] {
        required.formUnion(parent.required)
        current = parent
    }
    return required
}

/// Finds the nearest ancestor (or self) that has display hints.
func resolvedDisplayHints(
    for schema: TypeSchema,
    registry: [String: TypeSchema]
) -> DisplayHints? {
    if let hints = schema.displayHints { return hints }
    var current = schema
    while let parentId = current.parent, let parent = registry[parentId] {
        if let hints = parent.displayHints { return hints }
        current = parent
    }
    return nil
}

// MARK: - Code generation

func generateStruct(for schema: TypeSchema, registry: [String: TypeSchema]) -> String {
    let name = structName(for: schema.id)
    let fields = resolvedFields(for: schema, registry: registry)
    let required = resolvedRequired(for: schema, registry: registry)
    let hints = resolvedDisplayHints(for: schema, registry: registry)

    var out = ""

    // File-level comment (struct header)
    out += "/// ``\(name)`` — typed wrapper for `\(schema.id)` items.\n"
    if let desc = schema.description {
        out += "///\n/// \(desc)\n"
    }
    if let parentId = schema.parent {
        out += "///\n/// Inherits all fields from ``\(structName(for: parentId))``.\n"
    }
    if let hints {
        let parts = [
            hints.titleField.map { "title: `\($0)`" },
            hints.bodyField.map { "body: `\($0)`" },
        ].compactMap { $0 }
        if !parts.isEmpty {
            out += "///\n/// Display hints — \(parts.joined(separator: ", ")).\n"
        }
    }

    out += "public struct \(name): MarfaItem {\n"

    // Static type identifier
    out += "    public static let typeIdentifier = \"\(schema.id)\"\n\n"

    // Backing item
    out += "    /// The underlying generic item from the Marfa API.\n"
    out += "    public let item: Item\n\n"

    // Typed property accessors
    if !fields.isEmpty {
        out += "    // MARK: - Properties\n\n"
    }
    for (key, field) in fields {
        let isRequired = required.contains(key)
        let swiftName = camelCase(key)
        let type_ = swiftType(for: field, required: isRequired)

        // Doc comment
        if let desc = field.description {
            out += "    /// \(desc)\n"
        }
        // Enum values hint
        if field.type == "enum", let values = field.enumValues, !values.isEmpty {
            out += "    /// Allowed values: \(values.map { "`\($0)`" }.joined(separator: ", ")).\n"
        }
        // Array items hint
        if field.type == "array", let items = field.itemsType {
            out += "    /// Element type: `\(items)`.\n"
        }

        if isRequired {
            // Required: force-unwrap with a fatalError so codegen contract is clear
            // (init? already validates required fields are present).
            let extraction = extractionExpr(swiftName: swiftName, fieldKey: key, field: field, required: true)
            out += "    public var \(swiftName): \(type_) { \(extraction) }\n\n"
        } else {
            let extraction = extractionExpr(swiftName: swiftName, fieldKey: key, field: field, required: false)
            out += "    public var \(swiftName): \(type_) { \(extraction) }\n\n"
        }
    }

    // Designated init from generic Item
    out += "    // MARK: - Init\n\n"
    out += "    /// Returns `nil` if `item.type` does not match `\(schema.id)`\n"
    out += "    /// or a required field is missing from `item.properties`.\n"
    out += "    public init?(from item: Item) {\n"
    out += "        guard item.type == Self.typeIdentifier else { return nil }\n"
    for key in required.sorted() {
        let prop = requiredCheckExpr(fieldKey: key, field: fields.first(where: { $0.key == key })?.value)
        out += "        guard \(prop) else { return nil }\n"
    }
    out += "        self.item = item\n"
    out += "    }\n\n"

    // toProperties() — builds the properties dict for create/update
    out += "    /// Returns the typed properties as a ``JSONValue`` dictionary,\n"
    out += "    /// suitable for ``CreateItemInput`` or ``ItemsNamespace/update(id:properties:options:)``.\n"
    out += "    public func toProperties() -> [String: JSONValue] {\n"
    out += "        var props: [String: JSONValue] = [:]\n"
    for (key, field) in fields {
        let isRequired = required.contains(key)
        let swiftName = camelCase(key)
        let assignment = propertyAssignment(swiftName: swiftName, fieldKey: key, field: field, required: isRequired)
        out += "        \(assignment)\n"
    }
    out += "        return props\n"
    out += "    }\n"

    out += "}\n"
    return out
}

/// Generates the expression that reads a typed value from item.properties.
func extractionExpr(swiftName: String, fieldKey: String, field: FieldDefinition, required: Bool) -> String {
    let raw = "item.properties[\"\(fieldKey)\"]"
    switch field.type {
    case "string", "enum":
        return required
            ? "\(raw)?.stringValue ?? \"\""
            : "\(raw)?.stringValue"
    case "number":
        return required
            ? "\(raw)?.doubleValue ?? 0"
            : "\(raw)?.doubleValue"
    case "integer":
        return required
            ? "\(raw)?.intValue ?? 0"
            : "\(raw)?.intValue"
    case "boolean":
        return required
            ? "\(raw)?.boolValue ?? false"
            : "\(raw)?.boolValue"
    case "array":
        let items = field.itemsType ?? "string"
        switch items {
        case "number": return required
            ? "\(raw)?.arrayValue?.compactMap { $0.doubleValue } ?? []"
            : "\(raw)?.arrayValue?.compactMap { $0.doubleValue }"
        case "integer": return required
            ? "\(raw)?.arrayValue?.compactMap { $0.intValue } ?? []"
            : "\(raw)?.arrayValue?.compactMap { $0.intValue }"
        default: return required
            ? "\(raw)?.arrayValue?.compactMap { $0.stringValue } ?? []"
            : "\(raw)?.arrayValue?.compactMap { $0.stringValue }"
        }
    case "object":
        return required
            ? "\(raw)?.dictionaryValue ?? [:]"
            : "\(raw)?.dictionaryValue"
    default:
        return required ? "\(raw)?.stringValue ?? \"\"" : "\(raw)?.stringValue"
    }
}

/// Generates a Bool guard expression verifying a required field is present.
func requiredCheckExpr(fieldKey: String, field: FieldDefinition?) -> String {
    let raw = "item.properties[\"\(fieldKey)\"]"
    switch field?.type ?? "string" {
    case "number": return "\(raw)?.doubleValue != nil"
    case "integer": return "\(raw)?.intValue != nil"
    case "boolean": return "\(raw)?.boolValue != nil"
    default: return "\(raw)?.stringValue != nil"
    }
}

/// Generates the statement that writes a typed property into the props dict.
func propertyAssignment(swiftName: String, fieldKey: String, field: FieldDefinition, required: Bool) -> String {
    switch field.type {
    case "string", "enum":
        if required {
            return "props[\"\(fieldKey)\"] = .string(\(swiftName))"
        } else {
            return "if let v = \(swiftName) { props[\"\(fieldKey)\"] = .string(v) }"
        }
    case "number":
        if required {
            return "props[\"\(fieldKey)\"] = .double(\(swiftName))"
        } else {
            return "if let v = \(swiftName) { props[\"\(fieldKey)\"] = .double(v) }"
        }
    case "integer":
        if required {
            return "props[\"\(fieldKey)\"] = .int(\(swiftName))"
        } else {
            return "if let v = \(swiftName) { props[\"\(fieldKey)\"] = .int(v) }"
        }
    case "boolean":
        if required {
            return "props[\"\(fieldKey)\"] = .bool(\(swiftName))"
        } else {
            return "if let v = \(swiftName) { props[\"\(fieldKey)\"] = .bool(v) }"
        }
    case "array":
        // Arrays are always optional in toProperties (emit only if non-empty)
        let items = field.itemsType ?? "string"
        let wrap: String
        switch items {
        case "number": wrap = ".double($0)"
        case "integer": wrap = ".int($0)"
        default: wrap = ".string($0)"
        }
        if required {
            return "props[\"\(fieldKey)\"] = .array(\(swiftName).map { \(wrap) })"
        } else {
            return "if let v = \(swiftName), !v.isEmpty { props[\"\(fieldKey)\"] = .array(v.map { \(wrap) }) }"
        }
    case "object":
        if required {
            return "props[\"\(fieldKey)\"] = .dictionary(\(swiftName))"
        } else {
            return "if let v = \(swiftName) { props[\"\(fieldKey)\"] = .dictionary(v) }"
        }
    default:
        if required {
            return "props[\"\(fieldKey)\"] = .string(\(swiftName))"
        } else {
            return "if let v = \(swiftName) { props[\"\(fieldKey)\"] = .string(v) }"
        }
    }
}

// MARK: - Main

/// Walks up from the current working directory looking for `Package.swift`,
/// matching the pattern used by `codegen-wire`. Needed because
/// `CommandLine.arguments[0]` under `swift run` resolves to the build output
/// path, not the scripts directory.
func locateRepoRoot() -> URL {
    var url = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
    for _ in 0..<8 {
        if FileManager.default.fileExists(atPath: url.appendingPathComponent("Package.swift").path) {
            return url
        }
        url = url.deletingLastPathComponent()
    }
    fatalError("could not locate Package.swift starting from \(FileManager.default.currentDirectoryPath)")
}

let repoRoot = locateRepoRoot()
let typesDir = repoRoot.appendingPathComponent("scripts/MarfaCodegenCore/core-types")
let outputDir = repoRoot
    .appendingPathComponent("Sources/MarfaSDK/DomainModels/Generated")

let decoder = JSONDecoder()

// Load all type schemas
var schemas: [String: TypeSchema] = [:]
let typeFiles = (try? FileManager.default.contentsOfDirectory(
    at: typesDir, includingPropertiesForKeys: nil
))?.filter { $0.pathExtension == "json" } ?? []

for file in typeFiles {
    guard let data = try? Data(contentsOf: file),
          let schema = try? decoder.decode(TypeSchema.self, from: data)
    else {
        print("warning: could not parse \(file.lastPathComponent)")
        continue
    }
    schemas[schema.id] = schema
}

// Filter: active types only (no _deferred)
let activeSchemas = schemas.values
    .filter { $0.deferred != true }
    .sorted { $0.id < $1.id }

print("generating \(activeSchemas.count) domain model structs…")

// Ensure output dir exists
try? FileManager.default.createDirectory(at: outputDir, withIntermediateDirectories: true)

// Prune stale generated files
let expectedFiles = Set(activeSchemas.map { "\(structName(for: $0.id)).swift" })
let existingFiles = (try? FileManager.default.contentsOfDirectory(
    at: outputDir, includingPropertiesForKeys: nil
))?.filter { $0.pathExtension == "swift" } ?? []
for file in existingFiles where !expectedFiles.contains(file.lastPathComponent) {
    try? FileManager.default.removeItem(at: file)
    print("  pruned \(file.lastPathComponent)")
}

// Generate each struct
var generatedCount = 0
for schema in activeSchemas {
    let name = structName(for: schema.id)
    let outputFile = outputDir.appendingPathComponent("\(name).swift")

    let body = generateStruct(for: schema, registry: schemas)
    let header = """
    // Code generated by codegen-domain; DO NOT EDIT.
    // Source: scripts/core-types/\(schema.id.replacingOccurrences(of: ".", with: "_") + ".json" /* filename hint */)
    // Type ID: \(schema.id)\(schema.parent != nil ? " (parent: \(schema.parent!))" : "")
    // To regenerate: `./scripts/sync-types.sh` (or `swift run codegen-domain` if the snapshot is current).

    import Foundation

    """

    let content = header + body
    try content.write(to: outputFile, atomically: true, encoding: .utf8)
    print("  \(schema.id) → \(name).swift")
    generatedCount += 1
}

print("done — \(generatedCount) files written to \(outputDir.path)")

// MARK: - The runtime platform registry

// Domain-model structs are emitted for `core.*` only, because the system types
// are hand-written for their closed enums. The *registry* needs both: a device
// validating a write, or resolving a subtype, has to know about every type the
// platform ships, and `system.connection` rows reach a local store like any
// other. So the system schemas are loaded here rather than into `schemas`,
// which would make the generator above start emitting structs that are
// deliberately hand-written.
let systemDir = typesDir.appendingPathComponent("system")
var registrySchemas = schemas
for file in (try? FileManager.default.contentsOfDirectory(
    at: systemDir, includingPropertiesForKeys: nil
))?.filter({ $0.pathExtension == "json" }) ?? [] {
    guard let data = try? Data(contentsOf: file),
          let schema = try? decoder.decode(TypeSchema.self, from: data)
    else {
        print("warning: could not parse system/\(file.lastPathComponent)")
        continue
    }
    registrySchemas[schema.id] = schema
}

func swiftFieldType(_ declared: String) -> String {
    // The registry's enum spells `enum` as `explicitEnum`, because `enum` is a
    // keyword; every other case is the declared name unchanged.
    declared == "enum" ? "explicitEnum" : declared
}

func quoted(_ text: String) -> String {
    "\"" + text.replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\"", with: "\\\"") + "\""
}

let registryTypes = registrySchemas.values
    .filter { $0.deferred != true }
    .sorted { $0.id < $1.id }

var registryBody = ""
for schema in registryTypes {
    let fields = resolvedFields(for: schema, registry: registrySchemas)
    let required = resolvedRequired(for: schema, registry: registrySchemas)
    let hints = resolvedDisplayHints(for: schema, registry: registrySchemas)

    var fieldLines: [String] = []
    for (name, field) in fields.sorted(by: { $0.key < $1.key }) {
        var parts = ["type: .\(swiftFieldType(field.type))"]
        if let values = field.enumValues, !values.isEmpty {
            parts.append("enumValues: [\(values.map(quoted).joined(separator: ", "))]")
        }
        if let maxItems = field.maxItems {
            parts.append("maxItems: \(maxItems)")
        }
        if required.contains(name) {
            parts.append("isRequired: true")
        }
        fieldLines.append("                \(quoted(name)): .init(\(parts.joined(separator: ", "))),")
    }

    var leading = ["id: \(quoted(schema.id))"]
    if let parent = schema.parent {
        leading.append("parent: \(quoted(parent))")
    }
    var trailing: [String] = []
    if let title = hints?.titleField {
        trailing.append("titleField: \(quoted(title))")
    }
    if let body = hints?.bodyField {
        trailing.append("bodyField: \(quoted(body))")
    }
    trailing.append("schemaVersion: \(schema.version)")

    let fieldsArgument = fieldLines.isEmpty
        ? "fields: [:]"
        : "fields: [\n\(fieldLines.joined(separator: "\n"))\n            ]"
    let allParts = leading + [fieldsArgument] + trailing

    registryBody += "        \(quoted(schema.id)): MarfaTypeDefinition(\n"
    registryBody += "            " + allParts.joined(separator: ",\n            ") + "\n"
    registryBody += "        ),\n"
}

let registryDir = repoRoot.appendingPathComponent("Sources/MarfaSDK/Types/Registry/Generated")
try? FileManager.default.createDirectory(at: registryDir, withIntermediateDirectories: true)
let registryFile = registryDir.appendingPathComponent("PlatformTypeRegistry.swift")

let registryContent = """
// Code generated by codegen-domain; DO NOT EDIT.
// Source: scripts/MarfaCodegenCore/core-types/ (core and system schemas)
// To regenerate: `./scripts/sync-types.sh` (or `swift run codegen-domain` if the snapshot is current).
//
// The type graph the SDK ships with, flattened. Each definition carries its
// own fields *and* every inherited one, because that is the set a write is
// validated against and walking the chain at validation time would repeat the
// work on every call. `parent` is kept so a query for a parent type can find
// its descendants.

import Foundation

enum PlatformTypeRegistry {
    static let definitions: [String: MarfaTypeDefinition] = [
\(registryBody)    ]
}
"""

try registryContent.write(to: registryFile, atomically: true, encoding: .utf8)
print("registry — \(registryTypes.count) types written to \(registryFile.path)")
